### ISSUE TITLE
cannot convert CEDE

### ISSUE THREAD

**Issue by jeremyzechar** [OasisLMF/ITWG---AIR-CEDE-to-OED-file#1] opened 2019-08-07 13:56 UTC
Hello @shivamspj, I tried converting a very simple CEDE (18 locations, 2 contracts) and receive the following output messages. 

> Process started!
> Loggging process started...
> AIR location data prepared for mapping...
> OED blank location file prepared...
> Error Check Log file

Here's the [conversion.log](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3477278/conversion.log)

I don't know if this is a bug or user error. Any help?

**Comment by shivamspj** [comment] 2019-08-08 07:43
Hi @jeremyzechar,
Apparently this error comes up when you are using python 3.x. This code is python 2.x compatible. Can you please confirm python 2.x version usage?

We will definitely help you if any other issue is there. Thanks for your cooperation.

**Comment by jeremyzechar** [comment] 2019-08-08 07:52
Yes, I'm using Python 2.7.15 via Anaconda. Could you put a SQL backup of
the database you used for testing on github?

Am Do., 8. Aug. 2019 um 09:43 Uhr schrieb shivamspj <
notifications@github.com>:

**Comment by shivamspj** [comment] 2019-08-08 08:00
Sure, we will be sharing it soon.

**Comment by sbarik5** [comment] 2019-08-08 08:10
Hi @jeremyzechar ,

Please find attached the sample database back up file we used. 
[AIRExp_SampleData.zip](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3480534/AIRExp_SampleData.zip)

let us know if you are able to use this and does it convert succesfully

**Comment by sbarik5** [comment] 2019-08-08 08:54
Also @jeremyzechar, this DB back up file we shared in only the exposure db that AIR shared. 
You must already be having AIR reference database - so we didn't send that.

**Comment by jeremyzechar** [comment] 2019-08-08 09:21
Hi, @shivamspj, Thanks. I can convert the sample data successfully but cannot convert, for example, 
[this database](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3480840/AIRExp_2019_ITWG_test.zip) (or others with real or synthetic data that I tried).

**Comment by sbarik5** [comment] 2019-08-08 10:16
Hi @jeremyzechar, Thank you for sharing the database. We replicated your issue.
We are looking into this to resolve and will update.

A probable issue could be due to CondNumber assignment. Your data does not contain any Layercondition, so a join query can get an empty table leading to this error. But we will confirm.

**Comment by jeremyzechar** [comment] 2019-08-13 10:42
Hi, @shivamspj & @sbarik5, any progress here? The review period ends in less than 3 weeks and I'd like to try the code on some additional CEDEs.

**Comment by shivamspj** [comment] 2019-08-13 10:53
Hi **@jeremyzechar** ,
We have confirmed the reason for the issue. It is because of empty tables (LayerCondition and Layer) in the database.
We are fixing this for both location and account file. We have started working on this from today, will update you once done.
In the meantime, you can test with CEDEs having at least one sub-limit and one layer terms defined.

**Comment by sbarik5** [comment] 2019-08-14 18:11
Hi @jeremyzechar,
Code changes has been done in the development branch "develop-cr" pending review/clean up. 
You may want to test using this branch i.e. by downloading from this branch. 
Once we have reviewed code, will keep it ready and merge with any other feedback we receive.

**Comment by jeremyzechar** [comment] 2019-08-15 09:13
Hi, @sbarik5 , I just tested using the development branch with the database I provided above. The location input file is now created successfully but there's an error when creating the account file:

> 2019-08-15 10:46:38,944 INFO Issue in reading AIR DB and creating account file
2019-08-15 10:46:38,946 ERROR 'ExposureSetSID'
Traceback (most recent call last):
  File "...\ITWG---AIR-CEDE-to-OED-file-develop-cr\src\account_pre_process.py", line 36, in AIR_account_read
    self.AIR_account_filetmp = self.ExposureSetName.merge(self.ContractID, on="ExposureSetSID", how='inner')
...
KeyError:  'ExposureSetSID'

I also tried with some addtional databases (some synthetic data, some cedant data) and haven't had any success (various errors). Shall I send you some additional CEDEs w/ which to test?

By the way, xceedance server, username, and pwds are stored in the config.ini you've posted in the development branch, I guess you want to remove those!

**Comment by sbarik5** [comment] 2019-08-16 09:10
Hi @jeremyzechar,
We are able to convert both account and location file with the CEDE you shared. Can you confirm that you are getting this error from this same CEDE or from additional CEDEs you tested?
As per the error log, the key(ExposureSetSID) on which the tables are joined seems not available. We checked and don't see issue with the code.

Yes, please share additional databases you referred to. 
Looking forward to hearing from you.

**Comment by jeremyzechar** [comment] 2019-08-16 10:00
My apologies, I had remnants of the old config.ini that were causing the ExposureSetSID error. So, like you, I can convert the CEDE I previously shared. Thanks for that!

But I cannot convert these CEDEs:
[Florida.zip](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3509044/Florida.zip) -- simulated all perils risks in Florida
[Japan.zip](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3509045/Japan.zip) -- 16 all perils risks in Japan
[EUWS.zip](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3509046/EUWS.zip) -- simulated EUWS risks

The corresponding logs are here: 
[conversion.EUWS.log](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3509054/conversion.EUWS.log)
[conversion.Florida.log](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3509055/conversion.Florida.log)
[conversion.Japan.log](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3509056/conversion.Japan.log)

I've also seen a different error with a client CEDE, but I won't share that one here; what's the best way to transmit that to you privately for testing?

**Comment by sbarik5** [comment] 2019-08-16 10:20
Thank you. We are looking into the new databases you shared.

**Comment by sbarik5** [comment] 2019-08-16 13:02
Hi @jeremyzechar,
We took care of the issues related to the new attached databases you attached and committed the codes to same branch. Could you please check if the CEDEs are successfully getting converted now? 
Effectively, here are the changes:
1) The CEDEs contained 'all peril' peril code (-1 in the database) which included Crop model related perils as well for example. We had not defined them. We took care of the same.
2) updated character encoding
3) Added Addressmatch for non-geocoded locations

**Comment by sbarik5** [comment] 2019-08-16 13:15
Hi @jeremyzechar , with the above changes, we hope that the issue with the client CEDE will also get resolved. If not, please share the conversion log for the client CEDE (if you can). Otherwise, we will talk about how to transfer the client CEDE. 
By the way, thank you for the detailed testing you have done so far..

**Comment by jeremyzechar** [comment] 2019-08-16 14:43
Thanks for the fixes! The client CEDE conversion previously failed due to character encoding, but now fails because the machine runs out of memory: 

[conversion.log](https://github.com/OasisLMF/ITWG---AIR-CEDE-to-OED-file/files/3510045/conversion.log)

This CEDE has 700K+ locations and 500K+ contracts, and I tried the conversion on a machine with 40GB RAM. What's the best way for me to transfer this CEDE to you for testing?

**Comment by sbarik5** [comment] 2019-08-16 16:29
Is it possible to fragment the backup file and load it onto your sftp drive you may be using for outside data sharing. Share the ftp site link with us with the login/password. We will download from there. 
You can give the details to my email: subhashis.barik@xceedance.com

**Comment by sbarik5** [comment] 2019-08-19 14:05
Hi @jeremyzechar, just wanted to check if you got a chance to review the suggested transfer method for the client CEDE..

**Comment by jeremyzechar** [comment] 2019-08-19 14:17
Sorry for the delay, just sent details to yr email.

**Comment by sbarik5** [comment] 2019-08-19 16:29
Thank you Jeremy for sending this over. Will let you know our findings tomorrow.

**Comment by sbarik5** [comment] 2019-08-21 20:31
Hi @jeremyzechar , 
Wanted to update you on the progress.
We are working on it, After some code changes, We are able to run the Client CEDE successfully. 
We have also done few code changes to optimize and improve performance so that it does not take very long time to convert big CEDE databases. 
We are currently testing the changes. If you would like to test, you could download from development-cr branch. You should not see conversion failures and memory issues now. Also the CEDEs will convert much faster. But the actual content of the files are being tested now - will provide you more update as we progress.

**Comment by sbarik5** [comment] 2019-08-23 18:10
Hi @jeremyzechar, sample output files have been tested. 
Few thousand locations now takes couple of minutes to complete. 
The 0.7 million locations CEDE converts successfully -takes around 25 minutes to convert.

**Comment by sbarik5** [comment] 2020-06-17 12:42
Attaching the offlien email from @jeremyzechar confirming successful faster conversion
[Uploading Offline Email.docx…]()

**Comment by shivamspj** [comment] 2020-06-17 12:48
![performance](https://user-images.githubusercontent.com/31476741/84899926-f5ad2600-b0c6-11ea-9129-c3ee0cdb5553.png)

**Closed by shivamspj** 2020-06-17 12:48 UTC
Labels: bug
